name: Build solution

on:
  workflow_call:
    inputs:
      release_type:        
        default: Release
        required: false
        type: string

      artifacts_path:
        default: ./artifacts
        required: false
        type: string

    outputs:
      artifact_name:
        value: ${{ jobs.build_solution.outputs.artifact_name }}
        description: Name of the generated artifact

env:
  artifact_name: build_artifact

jobs:
  build_solution:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.output.outputs.artifact_name }}
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup .NET    
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build solution
        run: |
          pwsh -File ./scripts/Build-Solution.ps1 -ReleaseType ${{ inputs.release_type }} -ArtifactsDir ${{ inputs.artifacts_path }}
                
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ inputs.artifacts_path }}
          retention-days: 1

      - name: Set ouptuts
        id: output
        run: |
          echo "artifact_name=${{ env.artifact_name }} >> $GITHUB_OUTPUT"
